assets:
  compression: false
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: true
  defaults:
    js:
      integrity: false
    css:
      integrity: false
    img:
      integrity: false
